name: 构建 Cursor DEB 包

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 0:00 运行（北京时间 8:00）
  workflow_dispatch:
    inputs:
      version:
        description: '指定版本号（可选）'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装依赖
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y wget dpkg fakeroot jq

      - name: 运行构建脚本
        run: |
          set -ex
          echo "开始构建 DEB 包..."
          chmod +x ./build_deb.sh
          ./build_deb.sh || { echo "构建脚本执行失败"; exit 1; }
          echo "构建脚本执行完成"
          
          # 检查构建结果
          echo "检查构建结果:"
          ls -la build/
          find build -name "*.deb" | while read file; do
            echo "构建的 DEB 包: $file ($(du -h "$file" | cut -f1))"
          done
          
          # 创建版本信息文件
          VERSION="${{ github.event.inputs.version || steps.check_version.outputs.latest_version }}"
          echo "版本: $VERSION-${GITHUB_SHA:0:7}" > build/version_info.txt
          echo "构建时间: $(date)" >> build/version_info.txt
          echo "提交: ${{ github.sha }}" >> build/version_info.txt
          echo "工作流: ${{ github.workflow }}" >> build/version_info.txt
        env:
          CURSOR_VERSION: ${{ github.event.inputs.version || steps.check_version.outputs.latest_version }}
          GIT_SHA: ${{ github.sha }}
      
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: 上传 DEB 包
        if: ${{ github.event_name != 'schedule' || steps.check_version.outputs.skip_build == 'false' }}
        uses: actions/upload-artifact@v4
        with:
          name: cursor-deb-v${{ github.event.inputs.version || steps.check_version.outputs.latest_version }}-${{ env.SHORT_SHA }}
          path: |
            build/cursor_*_amd64.deb
            build/version_info.txt
          retention-days: 90 